import Script from 'next/script';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Head from './head';

import "../styles/styles.scss";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <Head/>
      </head>
      <body className={`${inter.className} sm:min-w-[390px] 
        min-w-full flex min-h-full sm:p-0 sm:m-0`} >
          <div >
          {children}
        </div>
      </body>
    </html>
  );
};