import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import "../styles/styles.scss";
import Head from './head';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head/>
      <body className={`${inter.className} sm:min-w-[390px] 
        min-w-full flex min-h-full sm:p-0 sm:m-0`}>
        {children}
      </body>
    </html>
  )
};