import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Head from '../head';
import Mouse from '@/components/functionality/cursor';

import "../../styles/styles.scss";
import StoreProvider from '../storeProvider';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode 
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <head>
          <Head/>
        </head>
        <body className={`${inter.className} sm:min-w-[390px] 
          min-w-full flex min-h-full sm:p-0 sm:m-0`} 
          >
          <Mouse/>
          <div id="root" >
            {children}
          </div>
        </body>
      </html>
    </StoreProvider>
  );
};